#+TITLE: A Short Bio
#+AUTHOR: Stephen
#+DATE: 2015-06-25
#+SEQ_TODO: TODO(t) STARTED(s) WAITING(w) DELEGATED(g) APPT(a) | DONE(d) DEFERRED(f) CANCELLED(c)
#+HTML_DOCTYPE: html5
#+OPTIONS: toc:nil   
#+FILETAGS: blog org-mode hakyll haskell bootstrap howto
#+LATEX_CLASS: myfdparticle

* PhD Studies at University of Washington
  :PROPERTIES:
  :ID:       57688b26-170b-4b0a-8f0f-b5ee4b912a9c
  :END:
  

  I am currently a PhD student at the [[http://foster.uw.edu/][Foster School of Business]] at the [[http://www.uw.edu][University of Washington]].
  I am studying Operations Management within the [[http://foster.uw.edu/faculty-research/academic-departments/information-systems-and-operations-management/][Department of Information Systems and Operations Management (DISOM)]].
  My advisor, [[http://faculty.washington.edu/hmamani/][Hamed Mamani]], and I, are interested in solving problems in healthcare using machine learning and optimization.
  

* Previous Studies
  :PROPERTIES:
  :ID:       16894fa3-8e3f-437b-bf00-d7d2c046349b
  :END:
  
  Prior to my time at the UW, I started a Finance PhD at the [[http://www.simon.rochester.edu/index.aspx][University of Rochester's Simon School of Business]]. 
  I enjoyed my time there, but the research was not a good fit.
  I left with an MBA in 2012, transferring directly to the UW.

  During my undergraduate, I studient [[https://www.math.washington.edu/acms/][Applied and Computational Mathematical Sciences (ACMS)]] and [[https://econ.washington.edu/][Economics]] at the University of Washington.
  
  
